# Site settings
title: U.E.Ehondor
header-img: images/home-bg.jpg
email: uyi@ehondor.com
description: "Notes to self and techies alike."
baseurl: ""
url: "http://uyi.ehondor.com"
social_profiles:
  twitter: cyberuyi
  github: uehondor
  linkedin: uyioghosaehondor

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 10
exclude: [
  'Gem*',
  'Guardfile',
  'Gruntfile',
  'bower.json',
  'package.json',
  'node_modules',
  'less',
  'vendor'
]
source:       .
destination:  ./_site
layouts:      ./_layouts
