# Site settings
title: Uyi Ehondor
email: uyi@email.com
description: "Notes to self and techies alike."
baseurl: ""
url: "http://uyi.ehondor.com"

# Build settings
markdown: kramdown
permalink: pretty

# exclude: ['Guardfile','Gemfile.lock','Gemfile']
exclude: []

source:       ./app
destination:  ./_site
plugins:      ./app/_plugins
layouts:      ./app/_layouts
