# Site settings
title: Uyi Ehondor
email: uyi@email.com
description: "Notes to self and techies alike."
baseurl: ""
url: "http://uyi.ehondor.com"

# paths
paths:
  images: 'images'

# Build settings
markdown: kramdown
permalink: pretty

exclude: [
  'Gem*',
  'Guardfile',
  'Gruntfile',
  'bower.json',
  'package.json',
  'node_modules',
  'less',
  'vendor'
]

source:       .
destination:  ./_site
plugins:      ./_plugins
layouts:      ./_layouts
